# 💡 Lite Configuration for Standard Developer Laptops
# Usage: docker-compose -f docker-compose.yml -f docker-compose.lite.yml up -d
# 
# Target: Most developer laptops (≤16GB RAM), CI/testing environments
# Expected Performance: Stable execution, conservative resource usage

services:
  airflow-common: &airflow-common-lite
    environment:
      # Conservative Spark configuration
      SPARK_DRIVER_MEMORY: 512m
      SPARK_EXECUTOR_MEMORY: 512m
      SPARK_DRIVER_MAX_RESULT_SIZE: 256m
      SPARK_SQL_ADAPTIVE_COALESCE_PARTITIONS_MIN_PARTITION_SIZE: 8MB
      SPARK_SQL_ADAPTIVE_ADVISORY_PARTITION_SIZE: 32MB
      
      # Conservative JVM settings
      SPARK_DRIVER_JAVA_OPTIONS: >-
        -XX:+UseSerialGC 
        -XX:MaxRAMPercentage=75
        -Djava.security.egd=file:/dev/./urandom
      
      SPARK_EXECUTOR_JAVA_OPTIONS: >-
        -XX:+UseSerialGC 
        -XX:MaxRAMPercentage=75

  airflow-webserver:
    <<: *airflow-common-lite
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.5'

  airflow-scheduler:
    <<: *airflow-common-lite
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2'
        reservations:
          memory: 1G
          cpus: '1'

  airflow-worker:
    <<: *airflow-common-lite
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '1'
        reservations:
          memory: 1G
          cpus: '0.5'

  # Minimal database resources
  postgres:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
    environment:
      - POSTGRES_SHARED_BUFFERS=128MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=384MB
      - POSTGRES_WORK_MEM=8MB
      - POSTGRES_MAINTENANCE_WORK_MEM=64MB